CREATE TABLE food_waste (
    food_type VARCHAR(100),
    number_of_guests INT,
    event_type VARCHAR(100),
    quantity_of_food INT,
    storage_conditions VARCHAR(100),
    purchase_history VARCHAR(100),
    season VARCHAR(50),
    preparation_method VARCHAR(100),
    location VARCHAR(100),
    pricing VARCHAR(20),
    food_wastage_amount INT,
    food_consumed INT,
    waste_percentage DECIMAL(5,2),
    price_per_kg INT,
    revenue_loss INT,
    donation_possible VARCHAR(10),
    waste_category VARCHAR(20),
    event_size VARCHAR(20)
);


-- =====================================================
-- FoodConnect Analytics
-- SQL Business Analysis Queries
-- Author: Jayasree Chakraborty
-- Database: PostgreSQL
-- =====================================================

---------------------------------------------------------
-- Query 1: Count Total Records
-- Purpose: Find the total number of records in the dataset.
---------------------------------------------------------

SELECT COUNT(*) AS total_records
FROM food_waste;

---------------------------------------------------------
-- Query 2: View First 10 Records
-- Purpose: Verify that the data was imported correctly.
---------------------------------------------------------

SELECT *
FROM food_waste
LIMIT 10;

---------------------------------------------------------
-- Query 3: Check for NULL Values
-- Purpose: Identify missing values in the food_type column.
---------------------------------------------------------

SELECT *
FROM food_waste
WHERE food_type IS NULL;

---------------------------------------------------------
-- Query 4: Total Food Wasted
-- Purpose: Calculate the total quantity of food wasted.
---------------------------------------------------------

SELECT SUM(food_wastage_amount) AS total_food_wasted
FROM food_waste;

---------------------------------------------------------
-- Query 5: Total Revenue Loss
-- Purpose: Calculate overall financial loss due to food waste.
---------------------------------------------------------

SELECT SUM(revenue_loss) AS total_revenue_loss
FROM food_waste;

---------------------------------------------------------
-- Query 6: Average Waste Percentage
-- Purpose: Find the average percentage of food wasted.
---------------------------------------------------------

SELECT ROUND(AVG(waste_percentage),2) AS average_waste_percentage
FROM food_waste;

---------------------------------------------------------
-- Query 7: Average Number of Guests
-- Purpose: Calculate the average number of guests served.
---------------------------------------------------------

SELECT ROUND(AVG(number_of_guests),0) AS average_guests
FROM food_waste;

---------------------------------------------------------
-- Query 8: Food Waste by Food Type
-- Purpose: Identify which food category contributes the most waste.
---------------------------------------------------------

SELECT
    food_type,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY food_type
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 9: Food Waste by Event Type
-- Purpose: Analyze waste generated by different event types.
---------------------------------------------------------

SELECT
    event_type,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY event_type
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 10: Revenue Loss by Pricing Category
-- Purpose: Compare revenue loss across pricing levels.
---------------------------------------------------------

SELECT
    pricing,
    SUM(revenue_loss) AS total_revenue_loss
FROM food_waste
GROUP BY pricing
ORDER BY total_revenue_loss DESC;

---------------------------------------------------------
-- Query 11: Food Waste by Season
-- Purpose: Identify which season experiences the highest food waste.
---------------------------------------------------------

SELECT
    season,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY season
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 12: Food Waste by Location
-- Purpose: Compare food waste across different locations.
---------------------------------------------------------

SELECT
    location,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY location
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 13: Food Waste by Storage Condition
-- Purpose: Analyze how storage conditions affect food waste.
---------------------------------------------------------

SELECT
    storage_conditions,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY storage_conditions
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 14: Food Waste by Preparation Method
-- Purpose: Identify preparation methods associated with higher waste.
---------------------------------------------------------

SELECT
    preparation_method,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY preparation_method
ORDER BY total_waste DESC;

---------------------------------------------------------
-- Query 15: Total Food Consumed by Food Type
-- Purpose: Find the amount of food successfully consumed.
---------------------------------------------------------

SELECT
    food_type,
    SUM(food_consumed) AS total_food_consumed
FROM food_waste
GROUP BY food_type
ORDER BY total_food_consumed DESC;

---------------------------------------------------------
-- Query 16: Donation Analysis
-- Purpose: Count events where food donation is possible.
---------------------------------------------------------

SELECT
    donation_possible,
    COUNT(*) AS total_events
FROM food_waste
GROUP BY donation_possible;

---------------------------------------------------------
-- Query 17: Events with Above Average Food Waste
-- Purpose: Identify events having waste greater than the overall average.
---------------------------------------------------------

SELECT *
FROM food_waste
WHERE food_wastage_amount >
(
    SELECT AVG(food_wastage_amount)
    FROM food_waste
);

---------------------------------------------------------
-- Query 18: Average Waste by Event Type (HAVING)
-- Purpose: Display event types whose average waste exceeds 30 kg.
---------------------------------------------------------

SELECT
    event_type,
    ROUND(AVG(food_wastage_amount),2) AS average_waste
FROM food_waste
GROUP BY event_type
HAVING AVG(food_wastage_amount) > 30
ORDER BY average_waste DESC;

---------------------------------------------------------
-- Query 19: Categorize Waste Using CASE
-- Purpose: Classify food waste into Low, Medium and High categories.
---------------------------------------------------------

SELECT
    food_type,
    food_wastage_amount,
    CASE
        WHEN food_wastage_amount < 20 THEN 'Low'
        WHEN food_wastage_amount BETWEEN 20 AND 35 THEN 'Medium'
        ELSE 'High'
    END AS waste_level
FROM food_waste;

---------------------------------------------------------
-- Query 20: Rank Food Types by Total Waste
-- Purpose: Rank food categories based on total food waste.
---------------------------------------------------------

SELECT
    food_type,
    SUM(food_wastage_amount) AS total_waste,
    RANK() OVER (
        ORDER BY SUM(food_wastage_amount) DESC
    ) AS waste_rank
FROM food_waste
GROUP BY food_type;

---------------------------------------------------------
-- Query 21: Dense Rank Event Types by Revenue Loss
-- Purpose: Rank event types according to revenue loss.
---------------------------------------------------------

SELECT
    event_type,
    SUM(revenue_loss) AS total_revenue_loss,
    DENSE_RANK() OVER (
        ORDER BY SUM(revenue_loss) DESC
    ) AS revenue_rank
FROM food_waste
GROUP BY event_type;

---------------------------------------------------------
-- Query 22: Row Number by Revenue Loss
-- Purpose: Assign a unique row number based on revenue loss.
---------------------------------------------------------

SELECT
    event_type,
    revenue_loss,
    ROW_NUMBER() OVER (
        ORDER BY revenue_loss DESC
    ) AS row_num
FROM food_waste;

---------------------------------------------------------
-- Query 23: Running Total of Revenue Loss
-- Purpose: Calculate cumulative revenue loss.
---------------------------------------------------------

SELECT
    event_type,
    revenue_loss,
    SUM(revenue_loss) OVER (
        ORDER BY revenue_loss
    ) AS running_total
FROM food_waste;

---------------------------------------------------------
-- Query 24: CTE Example
-- Purpose: Calculate average food waste using a Common Table Expression.
---------------------------------------------------------

WITH average_waste AS
(
    SELECT
        event_type,
        AVG(food_wastage_amount) AS avg_waste
    FROM food_waste
    GROUP BY event_type
)

SELECT *
FROM average_waste
ORDER BY avg_waste DESC;

---------------------------------------------------------
-- Query 25: Create a View
-- Purpose: Create a reusable summary for Power BI reporting.
---------------------------------------------------------

CREATE OR REPLACE VIEW vw_food_waste_summary AS

SELECT
    food_type,
    SUM(food_wastage_amount) AS total_waste,
    SUM(revenue_loss) AS total_revenue_loss,
    ROUND(AVG(waste_percentage),2) AS avg_waste_percentage
FROM food_waste
GROUP BY food_type;

---------------------------------------------------------
-- Query 26: View Summary
-- Purpose: Display the created reporting view.
---------------------------------------------------------

SELECT *
FROM vw_food_waste_summary;

---------------------------------------------------------
-- Query 27: Top 5 Highest Waste Food Types
-- Purpose: Show the top 5 food categories with the highest waste.
---------------------------------------------------------

SELECT
    food_type,
    SUM(food_wastage_amount) AS total_waste
FROM food_waste
GROUP BY food_type
ORDER BY total_waste DESC
LIMIT 5;

---------------------------------------------------------
-- Query 28: Top 5 Highest Revenue Loss Locations
-- Purpose: Identify locations with the highest revenue loss.
---------------------------------------------------------

SELECT
    location,
    SUM(revenue_loss) AS total_revenue_loss
FROM food_waste
GROUP BY location
ORDER BY total_revenue_loss DESC
LIMIT 5;

---------------------------------------------------------
-- Query 29: Average Waste Percentage by Pricing
-- Purpose: Compare average waste percentages across pricing categories.
---------------------------------------------------------

SELECT
    pricing,
    ROUND(AVG(waste_percentage),2) AS avg_waste_percentage
FROM food_waste
GROUP BY pricing
ORDER BY avg_waste_percentage DESC;

---------------------------------------------------------
-- Query 30: Top 3 Food Types Within Each Season
-- Purpose: Rank food categories by waste within each season.
---------------------------------------------------------

SELECT *
FROM
(
    SELECT
        season,
        food_type,
        SUM(food_wastage_amount) AS total_waste,
        RANK() OVER(
            PARTITION BY season
            ORDER BY SUM(food_wastage_amount) DESC
        ) AS rank
    FROM food_waste
    GROUP BY season, food_type
) ranked
WHERE rank <= 3;